services:
  # Server container
  server:
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    environment:
      CRYPTO_CONFIG_KEY: "${CRYPTO_CONFIG_KEY}"
      SERVER_PASSWORD: "${SERVER_PASSWORD}"
    network_mode: host

  # Proxy containers
  proxy:
    build:
      context: .
      dockerfile: ./docker/proxy/Dockerfile
    network_mode: host
    environment: 
      PROXY_PASSWORD: "${PROXY_PASSWORD}"
