services:
  # Server container
  server:
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    environment:
      CRYPTO_CONFIG_KEY: "${CRYPTO_CONFIG_KEY}"
      TRUSTSTORE_PASSWORD: "${TRUSTSTORE_PASSWORD}"
      SERVER_PASSWORD: "${SERVER_PASSWORD}"
    network_mode: host

  # Proxy containers
  proxy:
    build:
      context: .
      dockerfile: ./docker/proxy/Dockerfile
      args:
        - MOVIE
    network_mode: host
    command: sleep 2
    environment:
      TRUSTSTORE_PASSWORD: "${TRUSTSTORE_PASSWORD}"
      PROXY_PASSWORD: "${PROXY_PASSWORD}"
